
name: cd
on:
  push:
    branches:
    - main

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [14]

    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: ${{ matrix.node }}

      - name: Install dependencies
        run: yarn

      - name: Yarn Link @nuxt/content fork
        run: |
          set -xe
          git clone --branch feat/octokit-middleware https://github.com/nuxt-content-github/content nuxt-content-fork
          cd nuxt-content-fork/packages/content && yarn && yarn link
          cd - && yarn link @nuxt/content

      - name: Generate
        run: yarn run generate
        env:
          G_APP_PRIVATE_KEY: ${{ secrets.G_APP_PRIVATE_KEY }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
